### ISSUE TITLE
setup_scene error

### ISSUE THREAD

**Issue by yuejunpeng** [snumprlab/realfred#5]
Thank you for your meaningful work!

We use alfred codebase and try to use your realfred scenes and tasks.
When we try to setup a scene, there occurs an error:

Traceback (most recent call last):
  File "/media/ps/7890d249-37e9-43de-b60c-084f829a18df/alfred/scripts/play_thor.py", line 76, in <module>
    env = ThorEnv()
          ^^^^^^^^^
  File "/media/ps/7890d249-37e9-43de-b60c-084f829a18df/alfred/env/thor_env.py", line 29, in __init__
    super().__init__(quality=quality)
  File "/home/ps/anaconda3/envs/ai2thor/lib/python3.12/site-packages/ai2thor/controller.py", line 529, in __init__
    scenes_in_build = self.scenes_in_build
                      ^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/ai2thor/lib/python3.12/site-packages/ai2thor/controller.py", line 607, in scenes_in_build
    event = self.step(action="GetScenesInBuild")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/ps/7890d249-37e9-43de-b60c-084f829a18df/alfred/env/thor_env.py", line 143, in step
    if "LookUp" in action['action']:
                   ~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'


The version of ai2thor is 4.3.0

Our code:


import time
from ai2thor.controller import Controller
from env.thor_env import ThorEnv
import os
import json
from os.path import join as pjoin
import argparse

def setup_scene(env, traj_data, r_idx, args, reward_type='dense'):
    '''
    intialize the scene and agent from the task info
    '''
    # scene setup
    scene_num = traj_data['scene']['scene_num']
    object_poses = traj_data['scene']['object_poses']
    dirty_and_empty = traj_data['scene']['dirty_and_empty']
    object_toggles = traj_data['scene']['object_toggles']

    scene_name = 'FloorPlan%d' % scene_num
    env.reset(scene_name)
    env.restore_scene(object_poses, object_toggles, dirty_and_empty)

    # initialize to start position
    env.step(dict(traj_data['scene']['init_action']))

    # print goal instr
    print("Task: %s" % (traj_data['turk_annotations']['anns'][r_idx]['task_desc']))

    # setup task for reward
    env.set_task(traj_data, args, reward_type=reward_type)

description = "Play the abstract text version of an ALFRED environment."
parser = argparse.ArgumentParser(description=description)
parser.add_argument("problem", nargs="?", default=None)
parser.add_argument("--controller", default="oracle", choices=["oracle", "oracle_astar", "mrcnn", "mrcnn_astar"])
parser.add_argument("--debug", action="store_true")
parser.add_argument('--load_receps', action="store_true")
parser.add_argument('--reward_config', type=str)
args = parser.parse_args()



env = ThorEnv()
# env.reset()
args.problem = "/media/ps/7890d249-37e9-43de-b60c-084f829a18df/alfworld/ALFWorld_Data/json_2.1.1"
root = args.problem
json_file = pjoin(root, 'traj_data.json')
with open(json_file, 'r') as f:
    traj_data = json.load(f)

setup_scene(env, traj_data, 0, args)

The traj_data.json in our code is sampled from your dataset.

**Comment by twoongg** [comment]
Hi @yuejunpeng!

Thank you for having an interest in our work!
It seems like you are working on ALFRED code base, which is compatible for ai2thor==2.1.0.

As our work is compatible with ai2thor==4.3.0, you can not use ALFRED code base.
for example you will notice the difference in [ThorEnv](https://github.com/snumprlab/realfred/blob/master/seq2seq/env/thor_env.py#L171).

You may run your script in [seq2seq](https://github.com/snumprlab/realfred/blob/master/seq2seq) baseline directory, and it would work.

Please let me know if you have any further questions.
Thanks.

**Comment by yuejunpeng** [comment]
OK. I'll try. Thank you!

**Comment by twoongg** [comment]
Closing this issue due to inactivity. Feel free to reopen this if you have any questions.
